language: objective-c
env: LC_CTYPE=en_US.UTF-8
before_install:
    - gem install cocoapods
    - gem install xcpretty

script: xcodebuild -workspace UITextSubClass.xcworkspace -scheme UITextSubClass -configuration Debug -sdk iphonesimulator ONLY_ACTIVE_ARCH=YES clean build test | xcpretty -c

notifications:
  email: false
